name: ClickableImages
version: '${project.version}'
main: me.lisacek.clickableimages.ClickableImages
author: Lisacek
api-version: 1.16
commands:
  clickableimages:
    description: "Create clickable images"
    aliases: ["clickableimage", "ci", "cimages", "cimg", "cmig", "cimage"]